version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: userNpg
      POSTGRES_PASSWORD: passNpg
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - minha-rede

  api:
    build:
      context: .
      dockerfile: Dockerfile.Api
    depends_on:
      - db
    ports:
      - "5082:5082"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=userNpg;Password=passNpg;Database=postgres"
    networks:
      - minha-rede

  console:
    build:
      context: .
      dockerfile: Dockerfile.Console
    depends_on:
      - db
    environment:
      ConnectionString: "Host=db;Port=5432;Username=userNpg;Password=passNpg;Database=postgres"
    networks:
      - minha-rede
    entrypoint: ["dotnet", "PracticeTestFoursys.Console.dll"] # Ajuste conforme necessário para iniciar o console

networks:
  minha-rede:
    driver: bridge
