// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracticeTestFoursys.Infra.Context;

#nullable disable

namespace PracticeTestFoursys.Infra.Migrations
{
    [DbContext(typeof(PositionContext))]
    [Migration("20240721044637_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PracticeTestFoursys.Domain.Entities.Position", b =>
                {
                    b.Property<string>("PositionId")
                        .HasColumnType("text")
                        .HasColumnName("positionid")
                        .HasAnnotation("Relational:JsonPropertyName", "positionId");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clientid")
                        .HasAnnotation("Relational:JsonPropertyName", "clientId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productid")
                        .HasAnnotation("Relational:JsonPropertyName", "productId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity")
                        .HasAnnotation("Relational:JsonPropertyName", "quantity");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("PositionId");

                    b.ToTable("positions");
                });
#pragma warning restore 612, 618
        }
    }
}
